"""added fullname in user table

Revision ID: 5d9caf93b219
Revises: 9f8f32b46921
Create Date: 2022-08-31 09:18:37.265425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9caf93b219'
down_revision = '9f8f32b46921'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'posts', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('fullname', sa.String(), nullable=True))
    op.alter_column('users', 'phone_number',
               existing_type=sa.INTEGER(),
               nullable=b'I00\n')
    op.create_foreign_key(None, 'votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.alter_column('users', 'phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'fullname')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    # ### end Alembic commands ###
