"""add image_url in profile table

Revision ID: 7797f2fb6c0c
Revises: 816d41e2a02f
Create Date: 2022-08-28 19:40:48.610431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7797f2fb6c0c'
down_revision = '816d41e2a02f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('image_url', sa.String(), nullable=True))
    op.alter_column('profile', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=b'I00\n')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profile', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('profile', 'image_url')
    # ### end Alembic commands ###
