"""added profile column in user table

Revision ID: 9b4aa4ad7da6
Revises: 700b799052a9
Create Date: 2022-08-31 01:03:44.358333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b4aa4ad7da6'
down_revision = '700b799052a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'profile_image_path', sa.String(), nullable=True))
    op.add_column('users', sa.Column(
        'profile_image_url', sa.String(), nullable=True))
    op.alter_column('users', 'phone_number',
                    existing_type=sa.VARCHAR(),
                    nullable=b'I00\n')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'profile_image_path')
    # ### end Alembic commands ###
